### ISSUE TITLE
What is the function of "bucket" in the scenario?

### ISSUE THREAD

**Issue by pineappleKID** [nathansttt/hog2#36]
As introduced in https://movingai.com/benchmarks/formats.html, the first column of `.scen` file means "bucket". But there is no explanation about "bucket".
"bucket" is used in `ScenarioLoader.cpp` and `ScenarioLoader.h` but I still have no idea how to use "bucket".
https://github.com/nathansttt/hog2/blob/PDB-refactor/apps/canonicalGrids/Sample.cpp will do something if `bucket > 0` but the value of `bucket` is not used.

I notice that, in general, the greater `bucket` is, the greater optimal path length will be but this is not always true in the scenario file.

Thanks in advance.

**Comment by nathansttt** [comment]
Buckets are just the optimal path length divided by 4. It's used for grouping similar-length paths together for statistical purposes - to get a larger sample size. My lab has been using this approach since this paper: https://webdocs.cs.ualberta.ca/~nathanst/papers/partialpathfinding.pdf
