### ISSUE TITLE
Invalid Characters in file names in build/XCode for Windows

### ISSUE THREAD

**Issue by lior8** [nathansttt/hog2#57]
Greetings,
Some of the file names in buid/XCode contain asterisks in their names, making them invalid paths in Windows and create problems when cloning and working with the repo.
An example for such file is: https://github.com/nathansttt/hog2/blob/PDB-refactor/build/XCode/hog2%20iPad/IDA*%20-%20IBEX%20copy-Info.plist
I am not sure how to address this and thus opened an issue instead of a pull request containing an appropriate fix.
Kind regards,
Lior.

**Comment by lior8** [comment]
I compiled a list of files I found:
./build/XCode/hog2 mac native demos/A* (Graph) copy3-Info.plist
./build/XCode/hog2 mac native demos/A* (Map) copy2-Info.plist
./build/XCode/hog2 mac native demos/hog2 mac native demos.xcodeproj/xcuserdata/nathanst.xcuserdatad/xcschemes/IDA*.xcscheme
./build/XCode/hog2 mac native demos/hog2 mac native demos.xcodeproj/xcuserdata/nathanst.xcuserdatad/xcschemes/A* (Map).xcscheme
./build/XCode/hog2 mac native demos/hog2 mac native demos.xcodeproj/xcuserdata/nathanst.xcuserdatad/xcschemes/A* (Graph).xcscheme
./build/XCode/hog2 mac native demos/A* (Graph) copy-Info.plist
./build/XCode/hog2 mac native demos/IDA* copy2-Info.plist
./build/XCode/hog2 mac native demos/A* (Graph) copy2-Info.plist
./build/XCode/hog2 mac native demos/A* (Map) copy-Info.plist
./build/XCode/hog2 mac native demos/IDA* copy-Info.plist
./build/XCode/hog2 mac native demos/A* (Map) copy3-Info.plist
./build/XCode/hog2 iPad/hog2 iPad.xcodeproj/xcshareddata/xcschemes/IDA* - IBEX.xcscheme
./build/XCode/hog2 iPad/IDA* - IBEX copy-Info.plist

**Comment by lior8** [comment]
Issue is not yet fixed.
PR #59 was rejected due to inconsistency with some internal files.
I'll try looking into git-hooks which will check it before committing so the issue won't reoccur.

**Comment by nathansttt** [comment]
Resolved by latest commit.
