### ISSUE TITLE
Windows Invalid Characters Left in Some Paths in Filenames

### ISSUE THREAD

**Issue by lior8** [nathansttt/hog2#62]
This is a followup to issue #57 and commit fc8635f which addressed most of them, but not all.

Some files are left with a '*' in there name which are as follows:
- build/XCode/hog2 iPad/hog2 iPad.xcodeproj/xcshareddata/xcschemes/IDA* - IBEX.xcscheme
- build/XCode/hog2 mac native demos/hog2 mac native demos.xcodeproj/xcuserdata/nathanst.xcuserdatad/xcschemes/A* (Graph).xcscheme
- build/XCode/hog2 mac native demos/hog2 mac native demos.xcodeproj/xcuserdata/nathanst.xcuserdatad/xcschemes/A* (Map).xcscheme
- build/XCode/hog2 mac native demos/hog2 mac native demos.xcodeproj/xcuserdata/nathanst.xcuserdatad/xcschemes/IDA*.xcscheme

**Comment by lior8** [comment]
@yazeedMohi I saw you fixed the last problem, could you please help me fix this one as well?

**Comment by nathansttt** [comment]
Further fixes just pulled into the repository.

**Comment by lior8** [comment]
Looks like it's working.
Thank you very much for your help.
